# Push-to-Talk Configuration
# This mode uses manual control (spacebar) for voice input
# No automatic voice activity detection is used

scenario: "realtime-push-to-talk"
description: "Manual push-to-talk mode using spacebar to control recording"

# Turn Detection Configuration  
turn_detection:
  type: null  # Disable automatic turn detection for push-to-talk
