# Semantic VAD Configuration
# This mode uses semantic voice activity detection
# The AI model determines when the user has finished speaking based on context

scenario: "realtime-semantic-vad"
description: "Semantic voice activity detection using AI to determine speech completion"

# Turn Detection Configuration
turn_detection:
  type: "semantic_vad"
  create_response: true  # Automatically create response when speech stops
  interrupt_response: true  # Allow interrupting ongoing AI response
