# Semantic VAD Configuration
# This mode uses semantic voice activity detection
# The AI model determines when the user has finished speaking based on context

scenario: "realtime-semantic-vad"
description: "Semantic voice activity detection using AI to determine speech completion"

# OpenAI Configuration
openai:
  model: "gpt-4o-realtime-preview"
  voice: "alloy"  # Options: alloy, ash, ballad, coral, echo, sage, shimmer, verse
  temperature: 0.8
  instructions: "You are a helpful AI assistant. Respond naturally and conversationally."

# Turn Detection Configuration
turn_detection:
  type: "semantic_vad"
  create_response: true  # Automatically create response when speech stops
  interrupt_response: true  # Allow interrupting ongoing AI response
  eagerness: medium  # Eagerness level for semantic VAD (low, medium, high)

# Audio Configuration
audio:
  sample_rate: 24000
  channels: 1
  chunk_size: 1024
  format: "pcm16"

# UI Configuration
ui:
  show_audio_messages: false
  show_system_messages: true
  show_debug_messages: false
