# Server VAD Configuration
# This mode uses server-side voice activity detection
# The server automatically detects speech based on silence periods

scenario: "realtime-server-vad"
description: "Server-side voice activity detection with automatic turn detection"

# Turn Detection Configuration
turn_detection:
  type: "server_vad"
  threshold: 0.5  # Range: 0.0-1.0. Higher = less sensitive, better for noisy environments
  prefix_padding_ms: 300  # Audio to include before detected speech (ms)
  silence_duration_ms: 500  # Duration of silence to detect speech stop (ms)
  create_response: true  # Automatically create response when speech stops
  interrupt_response: true  # Allow interrupting ongoing AI response
