# Sensitive Server VAD Configuration
# This mode uses server-side VAD with high sensitivity settings
# Good for quiet environments or soft-spoken users

scenario: "realtime-server-vad"
description: "High sensitivity server VAD for quiet environments"

# Turn Detection Configuration
turn_detection:
  type: "server_vad"
  threshold: 0.3  # Lower threshold = more sensitive
  prefix_padding_ms: 200  # Less padding for faster response
  silence_duration_ms: 300  # Shorter silence detection for quicker turns
  create_response: true
  interrupt_response: true
