# Robust Server VAD Configuration
# This mode uses server-side VAD with low sensitivity settings
# Good for noisy environments or when you want to avoid false triggers

scenario: "realtime-server-vad"
description: "Low sensitivity server VAD for noisy environments"

# Turn Detection Configuration
turn_detection:
  type: "server_vad"
  threshold: 0.7  # Higher threshold = less sensitive, good for noisy environments
  prefix_padding_ms: 500  # More padding to capture full context
  silence_duration_ms: 800  # Longer silence duration to avoid premature cutoff
  create_response: true
  interrupt_response: true 
